# Generated by Django 4.1.6 on 2023-02-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LisaApp', '0002_delete_trialcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
