# Generated by Django 4.1.6 on 2023-02-13 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LisaApp', '0003_trialcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upjunction',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='upjunction',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
