# Generated by Django 4.1.6 on 2023-05-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LisaApp', '0004_alter_upjunction_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
